template: |
  ## What's Changed

  $CHANGES

footer: |
  $CONTRIBUTORS

 categories:
  - title: New Features ✨
    labels:
      - feature
  - title: Bug Fixes 🐛
    labels:
      - bugfix
      - hotfix
  - title: Other Changes 🛠
    labels:
      - refactor
      - chore
      - "*"

exclude-labels:
  - ignore-for-release
  - bot

autolabeler:
  - label: 'chore'
    title: '/chore/i'
    branch: 
      - '/chore/i'
    files:
      - '*.md'
  - label: 'bugfix'
    title:
      - '/fix/i'
    body:
      - '/fix/i'
    branch:
      - '/fix/i'
  - label: 'feature'
    title: '/feature/i'
    branch:
      - '/feature/i'