changelog:
  exclude:
    labels:
      - bot
  categories:
    - title: New Features ✨
      labels:
        - feature
    - title: Bug Fixes 🐛
      labels:
        - bugfix
        - hotfix
    - title: Other Changes 🛠
      labels:
        - refactor
        - chore
        - "*"