name: Create PR

on:
  push:
    branches:
    - develop

jobs:
  create-PR:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: pull-request
      uses: repo-sync/pull-request@v2
      with:
        destination_branch: "master"
        pr_title: "[BOT] Production Release"
        pr_body: "Merge this PR for production release :rocket:"
        pr_label: "bot"
        pr_draft: true
        github_token: ${{ secrets.GITHUB_TOKEN }}