name: Production deploy PR

on: 
  push:
    branches:
      - develop

jobs:
  createPullRequest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          branch: develop
          base: master
          title: '[BOT] Production Deploy PR'
          body: |
            Update report
            - Updated with *today's* date
          labels: |
            ignore-for-release
            automated pr
          draft: true