name: Create PR

on:
  push:
    branches:
    - develop

jobs:
  create-PR:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: pull-request
      uses: repo-sync/pull-request@v2
      with:
        destination_branch: "master"
        pr_title: "[BOT] Production Release"
        pr_body: "Merge this PR for production release :rocket:"
        pr_label: "bot"
        pr_draft: true
        github_token: ${{ secrets.GITHUB_TOKEN }}

  update_release_draft:
    needs: [ create-PR ] 
    permissions:
      contents: read
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Create tag
        uses: actions/github-script@v6
        id: tag
        with:
          result-encoding: string
          script: |
            const offset = 9 * 60 * 60 * 1000;
            const YYYMMDDHHMM = new Date(Date.now() + offset).toISOString().replace(/[^0-9]/g, '').slice(0, -5);
            return YYYMMDDHHMM;
      - uses: release-drafter/release-drafter@v5
        with:
          name: "${{ steps.tag.outputs.result }}"
          tag: ${{ steps.tag.outputs.result }}
          # publish: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}