on:
  push:
    branches:
    - develop

jobs:
  pull-request:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: pull-request
      uses: repo-sync/pull-request@v2
      with:
        destination_branch: "master"
        pr_title: "Pulling ${{ github.ref }} into master"
        pr_body: ":crown: *An automated PR*"
        pr_label: "ignore-for-release,bot"
        pr_draft: true
        github_token: ${{ secrets.GITHUB_TOKEN }}