name: Release Note

on: 
  push:
    branches:
      - master
  
jobs:
  release-note:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Create tag
        uses: actions/github-script@v6
        id: tag
        with:
          result-encoding: string
          script: |
            const offset = 9 * 60 * 60 * 1000;
            const YYYMMDDHHMM = new Date(Date.now() + offset).toISOString().replace(/[^0-9]/g, '').slice(0, -5);
            return YYYMMDDHHMM;
 
      - name: Generate release note
        uses: softprops/action-gh-release@v1 
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          name: "${{ steps.tag.outputs.result }}"
          tag_name: ${{ steps.tag.outputs.result }}
          generate_release_notes: true
